version: '3.7'
 
services:
  # AI Dashboard main application
  web:
    build:
      context: ./django_project
      dockerfile: ./env/web/Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 -t 86400 --workers 4
    privileged: true
    volumes:
      - static_volume:/home/app/web/static
      - env_data:/home/app/env
      - type: bind
        source: "./django_project/media/"
        target: "/home/app/media"
      - type: bind
        source: "./tools/"
        target: "/home/app/web/tools"
      - /dev/bus/usb:/dev/bus/usb:rw
    expose:
      - 8000
    ports:
      - 6006:6006
    environment:
      ALLOWED_HOSTS: "localhost ${ALLOWED_HOSTS}"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: [utility, compute, video]

  # Database
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

  # Front-end application
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1317:80
    depends_on:
      - web

  # Jupyter Notebook TensorFlow
  jupyter_notebook_tf:
    build: "./django_project/env/jupyter_notebook_tf/"
    volumes:
      - type: bind
        source: "./django_project/media/notebooks/"
        target: "/tf/work"
      - type: bind
        source: "./django_project/media/dataset/"
        target: "/tf/data"
      - type: bind
        source: "./django_project/app/machine_learning/lib/"
        target: "/tf/lib"
    ports:
      - 35000:8888
    environment:
      AI_DASHBORARD_IPADDR: ${ALLOWED_HOSTS}
    env_file:
      - ./django_project/env/jupyter_notebook_tf/.env
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             device_ids: ['0']
             capabilities: [gpu]

volumes:
  postgres_data:
  static_volume:
  env_data:
