# Generated by Django 4.0 on 2025-11-24 04:10

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelSDK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='AI Model SDK Name')),
                ('ai_model_sdk_zip', models.FileField(max_length=512, upload_to=app.models.ai_model_sdk_path)),
                ('ai_model_sdk_dir', models.CharField(blank=True, max_length=512, verbose_name='')),
                ('ai_model_sdk_dir_offset', models.CharField(blank=True, max_length=512, verbose_name='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='DatasetName')),
                ('dataset_type', models.CharField(choices=[('None', 'None'), ('Image', 'Image'), ('Table', 'Table'), ('Time Series', 'Time Series')], default='None', max_length=32)),
                ('dataset_dir', models.CharField(blank=True, max_length=512, verbose_name='Dataset directory in the Project directory')),
                ('dataset_dir_offset', models.CharField(blank=True, max_length=512, verbose_name='')),
                ('train_zip', models.FileField(max_length=512, upload_to=app.models.train_dataset_path)),
                ('valid_zip', models.FileField(blank=True, max_length=512, null=True, upload_to=app.models.validation_dataset_path)),
                ('test_zip', models.FileField(blank=True, max_length=512, null=True, upload_to=app.models.test_dataset_path)),
                ('meta_zip', models.FileField(blank=True, max_length=512, null=True, upload_to=app.models.meta_dataset_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_status', models.CharField(choices=[('None', 'None'), ('Preparing', 'Preparing'), ('Processing', 'Processing'), ('Done', 'Done')], default='None', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ProjectName')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('hash', models.CharField(max_length=128, verbose_name='Project hash')),
            ],
        ),
        migrations.CreateModel(
            name='MlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ModelName')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('hash', models.CharField(max_length=128, verbose_name='Model hash')),
                ('dataset_pickle', models.CharField(blank=True, max_length=512, verbose_name='Dataset Object (*.pkl)')),
                ('model_dir', models.CharField(max_length=1024, verbose_name='Model Directory')),
                ('status', models.TextField(verbose_name='Status')),
                ('training_pid', models.IntegerField(default=None, null=True, verbose_name='Training worker PID')),
                ('tensorboard_pid', models.IntegerField(default=None, null=True, verbose_name='Tensorboard worker PID')),
                ('ai_model_sdk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.aimodelsdk', verbose_name='AIModelSDK')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dataset', verbose_name='Dataset')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='aimodelsdk',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='Project'),
        ),
    ]
