# Generated by Django 4.0 on 2025-12-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='model_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Model Type'),
        ),
    ]
