# Generated by Django 4.0 on 2025-12-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mlmodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelsdk',
            name='model_type',
            field=models.CharField(blank=True, max_length=128, verbose_name='Model Type'),
        ),
    ]
