# Generated by Django 4.0 on 2025-12-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_aimodelsdk_model_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlmodel',
            name='model_type',
        ),
    ]
