# Generated by Django 4.0 on 2025-12-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_operationjob_id_alter_operationstep_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationjob',
            name='job_type',
            field=models.CharField(choices=[('TRAINING_RUN', 'TRAINING_RUN'), ('PROJECT_CREATE', 'PROJECT_CREATE'), ('MODEL_CREATE', 'MODEL_CREATE')], max_length=64),
        ),
    ]
