# Generated by Django 4.0 on 2025-12-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_operationjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationjob',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
