# Generated by Django 4.0 on 2025-12-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_operationjob_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationjob',
            name='job_type',
            field=models.CharField(choices=[('TRAINING_RUN', 'TRAINING_RUN'), ('PROJECT_CREATE', 'PROJECT_CREATE'), ('MODEL_CREATE', 'MODEL_CREATE'), ('INFERENCE_RUN', 'INFERENCE_RUN')], max_length=64),
        ),
    ]
